### ISSUE TITLE
SevLauncher: Add static IPV4 to virtual machines

### ISSUE THREAD

**Issue by solohin** [p2pcloud/p2pcloud#4]
So miner's machine might have a subnet attached to it. Development machines are on Hetzner and it looks like this: 
<img width="574" alt="Screen Shot 2022-08-12 at 1 47 18 PM" src="https://user-images.githubusercontent.com/8990432/184414968-fd24a69e-d805-420c-a971-f540098b6443.png">

Requrements:
- VM should not be able to take over another IP
- Zero configuration on VM's side
- Can be done on go, bash or both
- Machine doesn't know IP on launch. We can determine this randomly
- Would be great for IPV6 too, but this is not a requirement

Hetzner proposes forwarding:
[Article on Hetzner's wiki](https://docs.hetzner.com/robot/dedicated-server/ip/additional-ip-adresses/#individual-addresses) Also [this one](https://docs.hetzner.com/robot/dedicated-server/network/net-config-debian-ubuntu/)

Another good way is bridging:
```
#!/bin/bash
#systemctl stop NetworkManager
#systemctl stop systemd-networkd
#systemctl stop networking
#ip a flush eth0
#ip l add br0 type bridge
#ip l set eth0 master br0
#dhclient br0
n=${2-0}
net="-device virtio-net,netdev=network0,mac=52:54:00:11:11:1$n -netdev tap,id=network0,ifname=tap$n,script=`dirname $0`/QemuIfUp,downscript=no,vhost=on"

qemu-system-x86_64 -name nictest -enable-kvm \
   -cpu EPYC -machine q35 -smp 4,maxcpus=64 \
   -m 4096M,slots=5,maxmem=30G \
   -drive if=pflash,format=raw,readonly=on,file=/usr/share/OVMF/OVMF_CODE.fd \
   -drive file=${1-encrypted.qcow2},format=qcow2 \
   $net \
   -vga qxl -vnc :$((30+n)) -boot menu=on
```

QemuIfUp:
```
#!/bin/bash
n=${2-0}
net="-device virtio-net,netdev=network0,mac=52:54:00:11:11:1$n -netdev tap,id=network0,ifname=tap$n,script=`dirname $0`/QemuIfUp,downscript=no,vhost=on"

qemu-system-x86_64 -name nictest -enable-kvm \
   -cpu EPYC -machine q35 -smp 4,maxcpus=64 \
   -m 4096M,slots=5,maxmem=30G \
   -drive if=pflash,format=raw,readonly=on,file=/usr/share/OVMF/OVMF_CODE.fd \
   -drive file=${1-encrypted.qcow2},format=qcow2 \
   $net \
   -vga qxl -vnc :$((30+n)) -boot menu=on
```

**Comment by sza-1** [comment]
Ready. PR: #16.
