### ISSUE TITLE
SevLauncher: CPU and memory limits

### ISSUE THREAD

**Issue by solohin** [p2pcloud/p2pcloud#5]
Right now CPU and memory are [hard coded](https://github.com/p2pcloud/p2pcloud/blob/41662ba930fa6c6b397040533b5e8e435ea4b3ae/pkg/sevlauncher/launch.go#L80).

- [ ] Add CPU and mem limits to `SevLauncher` struct
- [ ] Figure out the best way to pass them into GetInstance or something like that. Maybe methods and then check their existence in the `Launch` method?
- [ ] In cmd/devserver you'll need to add a new ` VmTypeProviderIface` dev implementation

**Comment by sza-1** [comment]
Should we use these limits for maxcpus/maxmem, for initial cpus/mem, or for both initial and max?
